### ISSUE TITLE
[prototype] 피그마 프로토타입

### ISSUE THREAD

**Issue by wongbingg** [wongbingg/ios-wanted-PersonalScheduler#2]
## Description

Figma를 통해 앱 프로토타입 제작

## TODO
- [x] 1. 첫 로그인 화면
- [x] 2. 두번째 스케줄 리스트 화면
    - [x] 2-1. 필수 표시항목 [ 제목, 실행일시, 본문의 일부, +@ 더 보여줘도 상관없음]
    - [x] 2-2. 셀 스와이프를 통한 삭제
    - [x] 2-3. 현재 일시가 실행일~종료일 사이가 되면 연두색, 지나면 회색으로 표시
- [ ] 3. 스케줄을 저장, 수정할 수 있는 페이지 [ 제목, 실행일시 (시작일 ~ 종료일), 500자 이하 본문]

**Comment by wongbingg** [comment]
### 첫 로그인 화면 

<img width="250" alt="스크린샷 2023-01-09 오전 11 28 33" src="https://user-images.githubusercontent.com/95671495/211232457-13aa1156-f3a9-421c-96d8-b4d3027417df.png">

**Comment by wongbingg** [comment]
### 스케줄 리스트 화면 
<img width="250" alt="스크린샷 2023-01-12 오후 3 14 09" src="https://user-images.githubusercontent.com/95671495/211991559-6276e2f5-fc67-4031-a7d1-8cef4cf358eb.png">
